DEFAULT_MAX_WORKERS = 12
DEFAULT_SEARCH_MAX_WORKERS = 24
DEFAULT_PROBE_MAX_WORKERS = 6
DEFAULT_REQUEST_TIMEOUT = 15.0
DEFAULT_SEARCH_REQUEST_TIMEOUT = 8.0
DEFAULT_SEARCH_TIME_BUDGET = 60.0
DEFAULT_JS_TIMEOUT_SECONDS = 2.0
